name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  backup:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - 
